In [ ]:
"""
input data:
age	sex	bmi	children	smoker	region

output data:
charges

layers:
input layer - 6 nodes
hidden layer - 6 neurons
output layer - 1 neuron outputting a single float value (charges)

compilation:
optimizer=SGD
loss=MAE
metric=MAE

activation functions:
hidden layer=ReLU or NONE
output layer=NONE
"""

'\ninput data:\nage\tsex\tbmi\tchildren\tsmoker\tregion\n\noutput data:\ncharges\n\nlayers:\ninput layer - 6 nodes\nhidden layer - 6 neurons\noutput layer - 1 neuron outputting a single float value (charges)\n\ncompilation:\noptimizer=SGD\nloss=MAE\nmetric=MAE\n\nactivation functions:\nhidden layer=ReLU or NONE\noutput layer=NONE\n'

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("https://gist.githubusercontent.com/meperezcuello/82a9f1c1c473d6585e750ad2e3c05a41/raw/d42d226d0dd64e7f5395a0eec1b9190a10edbc03/Medical_Cost.csv")

In [ ]:
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
# data[['age', 'sex', 'bmi', 'children', 'smoker', 'region']]
for i in range(1338):
  if data['region'][i] == "northeast":
    data['region'][i] = 1.0
  elif data['region'][i] == "southeast":
    data['region'][i] = 2.0
  elif data['region'][i] == "southwest":
    data['region'][i] = 3.0
  elif data['region'][i] == "northwest":
    data['region'][i] = 4.0

  if data['sex'][i] == 'male':
    data['sex'][i] = 0.0
  else:
    data['sex'][i] = 1.0

  if data['smoker'][i] == 'no':
    data['smoker'][i] = 0.0
  else:
    data['smoker'][i] = 1.0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
data

      age  sex     bmi  children smoker region      charges
0      19  1.0  27.900         0    1.0    3.0  16884.92400
1      18  0.0  33.770         1    0.0    2.0   1725.55230
2      28  0.0  33.000         3    0.0    2.0   4449.46200
3      33  0.0  22.705         0    0.0    4.0  21984.47061
4      32  0.0  28.880         0    0.0    4.0   3866.85520
...   ...  ...     ...       ...    ...    ...          ...
1333   50  0.0  30.970         3    0.0    4.0  10600.54830
1334   18  1.0  31.920         0    0.0    1.0   2205.98080
1335   18  1.0  36.850         0    0.0    2.0   1629.83350
1336   21  1.0  25.800         0    0.0    3.0   2007.94500
1337   61  1.0  29.070         0    1.0    4.0  29141.36030

[1338 rows x 7 columns]

In [ ]:
# for i in range(1338):
#   data['']

In [ ]:
X = data.drop(columns='charges')
y = data['charges']
X_train, y_train, X_test, y_test = X.iloc[0:1070], y.iloc[0:1070], X.iloc[1070:], y.iloc[1070:]
X_train = np.asarray(X_train).astype('float32')
y_train = np.asarray(X_train).astype('float32')
X_test = np.asarray(X_test).astype('float32')
y_test = np.asarray(y_test).astype('float32')

X_train = tf.expand_dims(tf.constant(X_train, dtype=tf.float64), axis=0)
y_train = tf.expand_dims(tf.constant(y_train, dtype=tf.float64), axis=0)
X_test = tf.expand_dims(tf.constant(X_test, dtype=tf.float64), axis=0)
y_test = tf.expand_dims(tf.constant(y_test, dtype=tf.float64), axis=0)
y_test.shape

y_test.shape == X_test.shape
X_train.size

6420

In [ ]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(10),
  tf.keras.layers.Dense(10),
  tf.keras.layers.Dense(6)
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(lr=0.01),
    loss=tf.keras.losses.mae,
    metrics=["mae"])

model.fit(X_train, y_train, epochs=1000, verbose=0)

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)

In [ ]:
model.evaluate(X_test, y_test)
# np.array(y_test).max() - np.array(y_test).min()

#y_test
#pd.DataFrame.median()

9/9 [==============================] - 0s 2ms/step - loss: 13483.0732 - mae: 13483.0732

[13483.0732421875, 13483.0732421875]